title: Going Distances on one Boat!
description: Prerit's Blog

# url: http://prerit2010.github.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: prerit2010
   facebook: prerit2013
   twitter: 
   email: prerit2010@gmail.com

google_analytics: ""
